main/urls.py
from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('home/',HomeView.as_view(),name='home'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('debug/', DebugView.as_view(),name='debug'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/cv_submission/models.py
from django.db import models

class CV(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    cv_file = models.FileField(upload_to='cv_submissions/')

    def __str__(self):
        return self.name

main/models.py
from django.db import models

# Create your models here.

main/cv_submission/forms.py
from django import forms
from.models import CV

class CVForm(forms.ModelForm):
    class Meta:
        model = CV
        fields = ('name', 'email', 'cv_file')

main/cv_submission/views.py
from django.shortcuts import render, redirect
from .forms import CVForm

def submit_cv(request):
    if request.method == 'POST':
        form = CVForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('cv_submission:success')
    else:
        form = CVForm()
    return render(request, 'cv_submission/submit_cv.html', {'form': form})

def submission_success(request):
    return render(request, 'cv_submission/submission_success.html')

main/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
import time

class HomeView(LoginRequiredMixin, View):
    template_name = "home.html"
    def get(self, request):
        return render(request, self.template_name)
class DebugView(TemplateView):
    template_name = 'debug.html'
class LogoutView(LoginRequiredMixin, TemplateView):
    success_url =reverse_lazy('user_auth:login')
    def get(self, request):
        time.sleep(2)
        logout(request)
        return redirect(self.success_url) 
# Create your views here.

main/templates/debug.html
<p>{{user.student.image.url}}</p>

main/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GradHunt | Exclusive Social App for Students</title>
    
    <link rel="stylesheet" href="{%static 'css/navigation.css'%}" />
    <!----===== Boxicons CSS ===== -->
    <link
      href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    />
  </head>
  <body>
    <header>
      <div class="logo">
        <h1 class="desktop-view">GRAD<span class="desktop-view">HUNT</span></h1>
        <h1 class="mobile-view">G<span class="mobile-view">H</span></h1>
      </div>
      <div class="hamburger">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </div>
      <!-- Search Bar -->
      <div class="search">
        <input type="text" placeholder="Search Here..." />
        <button class="btn"><i class="bx bx-search-alt-2"></i></button>
      </div>
      <!-- Navigation -->
      <nav class="nav-bar">
        <ul>
          <div class="search">
            <input type="text" placeholder="Search Here..." />
            <button class="btn"><i class="bx bx-search-alt-2"></i></button>
          </div>
          <li class="nav-link"><a href="">Home</a></li>
          <li class="nav-link"><a href="">Notifications</a></li>
        </ul>
      </nav>
    </header>
    <div class="container_sections">
      <section class="left_section">
        <div class="menu">
          <ul>
            <li>
              <a href="{% url 'BlogPost:blogpost' %}"><i class="bx bxl-blogger"></i>Blogs</a>
            </li>
            <li>
              <a href=""><i class="bx bx-bookmarks"></i>Bookmarks</a>
            </li>
            <li>
              <a href=""><i class="bx bx-calendar-event"></i>Events</a>
            </li>
            <li>
              <a href=""><i class="bx bx-chat"></i>Instant Messaging</a>
            </li>
            <li>
              <a href=""><i class="bx bx-bell"></i>Notifications</a>
            </li>
            <li>
              <a href=""><i class="bx bx-briefcase-alt"></i>Job Search</a>
            </li>
          </ul>
        </div>
      </section>
      <section class="middle_section">Hey</section>
      <section class="right_section">
        <div class="menu">
          <div class="profile_img">
            <img src="{{request.user.student.image.url}}" alt="" />
            <span>{{request.user.student.last_name}}</span>
          </div>
          <ul>
            <li>
              <a href=""><i class="fa-solid fa-gear fa-spin"></i>Settings</a>
            </li>
            <li>
              <a href=""><i class="bx bxl-mailchimp"></i>Send us Feedback</a>
            </li>
            <li>
              <a href="{%url 'main:logout'%}"
                ><i class="bx bx-log-out"></i>Logout</a
              >
            </li>
          </ul>
        </div>

        <div class="menu">
          <div class="topic">
            <span>Recent Activities</span>
          </div>
          <ul>
            <li>
              <a href=""><i class="fa-solid fa-gear fa-spin"></i>Settings</a>
            </li>
            <li>
              <a href=""><i class="bx bxl-mailchimp"></i>Send us Feedback</a>
            </li>
            <li>
              <a href=""><i class="bx bx-log-out"></i>Logout</a>
            </li>
          </ul>
        </div>

        <div class="menu online_friends">
          <div class="topic">
            <span>Online Friends</span>
          </div>
          <ul class="online_friends">
            <li>
              <img src="{% static 'default.jpg' %}" alt="" />
              <a>Donald Misaki</a>
            </li>
            <li>
              <img src="{% static 'default.jpg' %}" alt="" />
              <a>Donald Misaki</a>
            </li>
            <li>
              <img src="{% static 'default.jpg' %}" alt="" />
              <a>Donald Misaki</a>
            </li>
          </ul>
        </div>
      </section>
    </div>
  </body>
  <script src="js/navigation.js"></script>
</html>